# Generated by Django 4.2.10 on 2024-02-13 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSpaceTrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('id_workspace', models.CharField(blank=True, max_length=200)),
                ('api_key', models.CharField(blank=True, max_length=200)),
                ('secret', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TableTrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('id_table', models.CharField(blank=True, max_length=200)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.workspacetrello')),
            ],
        ),
        migrations.CreateModel(
            name='ListTrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('id_list', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('nouvelle_entree', 'Nouvelle entrée'), ('en_attente_de_saisie', 'En attente de saisie'), ('confirme', 'Confirmé'), ('a_retraiter', 'À retraiter'), ('injoignable', 'Injoignable'), ('a_relancer', 'À relancer'), ('rendez_vous_fixe', 'Rendez-vous fixé'), ('communique', 'Communiqué'), ('a_resoudre', 'À résoudre'), ('livre', 'Livré'), ('retourne', 'Retourné'), ('annule', 'Annulé'), ('a_verifier', 'À vérifier'), ('non_modifiable', 'Non modifiable')], default='En attente', max_length=50)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.tabletrello')),
            ],
        ),
        migrations.CreateModel(
            name='LabelTrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=50)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.tabletrello')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldTrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('id_field', models.CharField(blank=True, max_length=200)),
                ('field_type', models.CharField(max_length=50)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.tabletrello')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldOptionTrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('option_id', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(blank=True, max_length=200)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='models.customfieldtrello')),
            ],
        ),
    ]
