# Generated by Django 4.2.10 on 2024-02-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=200, unique=True)),
                ('nom_complet', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('addresse', models.CharField(max_length=200)),
                ('prix', models.IntegerField()),
                ('quantite', models.IntegerField()),
                ('date_reception', models.CharField(max_length=200)),
                ('produit', models.CharField(max_length=200)),
                ('numero_suivi', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('statut_commande', models.CharField(max_length=200)),
                ('city_ramassage_sendit', models.CharField(max_length=200)),
            ],
        ),
    ]
